# Generated by Django 6.1.1 on 2026-09-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_code_required'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='product_stock_non_negative',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='quantity',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='product_stock_non_negative'),
        ),
    ]
